### ISSUE TITLE
Values are reported in W, but should be kWh

### ISSUE THREAD

**Issue by Yorik-Code** [oziee/ha-solcast-rooftop#2]
It seems like the pulled values forecast are out by 3 orders of magnitude.
Forecast for tomorrow is 33kWh, but it shows as 33Wh..
Energy dashboard shows this as well. screenshots hopefully help.

![Screenshot at 2021-09-22 22-23-37](https://user-images.githubusercontent.com/11325212/134362649-63f73c28-e447-4289-af4d-766bc0483fe0.png)

Estimated Production screengrab taken.
![Screenshot at 2021-09-22 22-25-34](https://user-images.githubusercontent.com/11325212/134362674-1815ba66-0cbe-42eb-af17-7ce518a2ee1f.png)

.

**Comment by Yorik-Code** [comment]
I did see a couple of "/ 1000" in Const.py, but I really don't know enough about the rest of the integration to make that change myself and I assume that it is just for the Estimate Energy Production figures?

I'm pretty new to this part, sorry if I haven't provided the right information.

**Comment by oziee** [comment]
Hey @Yorik-Code 

In the solcast site settings for your home what does it have set for the inverter info?

![image](https://user-images.githubusercontent.com/1471841/134440803-ead0ce5a-b9fa-4c7a-a2b4-f47f96928f77.jpeg)

My values are all showing fine so I'm just wondering what might be happening

**Comment by oziee** [comment]
Mine too.. I can see that
Funny that my other add in has the same code and works fine.. but the rooftop add on is wrong

When I get home from work tonight I will fix it up

Thanks

**Comment by oziee** [comment]
Yes the rooftop returns the data in kWh compared to the other add in

So in the const.py file just delete the two lines that have the "/ 1000"... save.. delete the _pycach file and restart ha and all will be good

I'll update this code later as I can't from my iPhone

**Comment by oziee** [comment]
should be fixed now

**Comment by Yorik-Code** [comment]
Thanks very much for the quick reply and for taking the time to explain the fix to me. I'll review the code and see if I can work out how it all works. Slowly learning. :)
