### ISSUE TITLE
809 update seems to have stopped today's forecast, tomorrow is showing 

### ISSUE THREAD

**Issue by habuild** [oziee/ha-solcast-rooftop#4]
Hi oziee,
Nice work on the integration.
(you should probably add a changelog.md file, and look at version numbering. I think HA does year, month, release number for that month. As in 2021.9.2) that's just a small thing though.

The last update which removed past polling, I think. Seems to have stopped showing today's solar forecast(and any previous) .. Well at least after sunset (I didn't actually look earlier.) tomorrows is showing up.

Perhaps I messed up something.

**Comment by oziee** [comment]
It's not you.. it's the code

So there has been changes but I have not put to GitHub yet until I test it further

Currently this code if you restart HA the energy info only has data from "this" min onwards. 

The next update soon will display past 7 days and future 7 days.. and only poll the api when HA starts and then only between an hour Before sunrise and an hour after sunset

Hope to have the code up today or tomorrow
